"""empty message

Revision ID: e5977f959fab
Revises: 04a705442f9e
Create Date: 2020-08-15 17:06:58.271868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5977f959fab'
down_revision = '04a705442f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('desc', sa.String(length=200), nullable=False))
    op.drop_column('cms_role', 'decs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('decs', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('cms_role', 'desc')
    # ### end Alembic commands ###
